apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: audiobookshelf
  name: audiobookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobookshelf
  template:
    metadata:
      labels:
        app: audiobookshelf
    spec:
      containers:
      - image: ghcr.io/advplyr/audiobookshelf
        name: audiobookshelf
        ports:
          - containerPort: 3005
        envFrom:
          - configMapRef:
            name: configmap-env
        volumeMounts:
          - mountPath: "/audiobooks"
            name: audiobookshelf-storage
          - mountPath: "/podcasts"
            name: audiobookshelf-storage
          - mountPath: "/config"
            name: audiobookshelf-storage
          - mountPath: "/metadata"
            name: audiobookshelf-storage
         
      volumes:
        - name: audiobookshelf-storage
          persistentVolumeClaim:
            claimName: audiobookshelf-pvc