apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: audiobookshelf
  name: audiobookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobookshelf
  template:
    metadata:
      labels:
        app: audiobookshelf
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000

      containers:
      - image: ghcr.io/advplyr/audiobookshelf:2.19.2
        name: audiobookshelf
        ports:
          - containerPort: 3005

        envFrom:
          - configMapRef:
              name: configmap-env
        
        securityContext:
            allowPrivilegeEscalation: false

        volumeMounts:
          - mountPath: "/audiobooks"
            name: audiobookshelf-storage
          - mountPath: "/podcasts"
            name: audiobookshelf-storage
          - mountPath: "/config"
            name: audiobookshelf-storage
          - mountPath: "/metadata"
            name: audiobookshelf-storage
         
      volumes:
        - name: audiobookshelf-storage
          persistentVolumeClaim:
            claimName: audiobookshelf-pvc